#include "gemini_api_service.h"

// does not call the real Gemini API yet
std::string GeminiApiService::GenerateResponse(const std::string& prompt, const std::string& apiKey) {
	// if key or prompt missing
	if (apiKey.empty() || prompt.empty()){
		return "";
	}

	// gemini api endpoint
	std::string url = "https://generativelanguage.googleapis.com/v1beta/models/gemini-3-flash:generateContent";
	// request body (generated by gemini)
	std::string jsonBody = "{\"contents\": [{\"parts\": [{\"text\": \"" + prompt + "\"}]}]}";

	//send post request
	HttpResponse response = this->httpClient.PostJson(url, jsonBody, {
    	{"x-goog-api-key", apiKey}
	});
	if (!response.Ok()) { return ""; }
	
	// Request body: the prompt as the user text. Response: the model’s text (candidates[0].content.parts[0].text).

	std::string modelText = ""; // extract from response body
	size_t textKeyPos = response.body.find("\"text\""); 
	// logic for parsing from quote to quote here.
	if (textKeyPos != std::string::npos)
	{
		// find the colon after text
		size_t colonPos = response.body.find(':', textKeyPos);
		if (colonPos != std::string::npos)
		{
			// find the start quote after the colon
			size_t startQuote = response.body.find('"', colonPos);
			if (startQuote != std::string::npos)
			{
				// start after the quote
				size_t currentPos = startQuote + 1;

				// loop and find the end quote
				while (currentPos < response.body.length())
				{
					size_t endQuote = response.body.find('"', currentPos);
					if (endQuote == std::string::npos) {break;}
					
					// check to see if the quote is escaped, for cards that use quotes
					if (response.body[endQuote - 1] == '\\')
					{
						// keep searching further if a slash is there
						currentPos = endQuote + 1;
					} else {
						// output the text inbetween the quotes
						modelText = response.body.substr(startQuote + 1, endQuote - (startQuote + 1));
						break;
					}
				}
			}
		}
	}

	return modelText;
}
