rem --- GENERATED BY COPILOT -----------------------------------------
@echo off
setlocal

rem --- OUTPUT ---------------------------------------------------------
set OUT=Merken.exe
echo Building %OUT%

rem --- PATHS ----------------------------------------------------------
set MINGW=C:\mingw-w64
set WX=C:\wxWidgets
set PATH=%MINGW%\bin;%PATH%

rem --- INCLUDE / LIB PATHS -------------------------------------------
set INC=-I UI\include -I ThirdParty\boost-di -I ThirdParty\wxSQLite3\include -I %WX%\lib\gcc_lib\mswu -I %WX%\include
set LIB=-L %WX%\lib\gcc_lib

rem --- WXWIDGETS LIBS -------------------------------------------------
set WXLIBS= ^
    -lwxmsw32u_core ^
    -lwxbase32u ^
    -lwxpng ^
    -lwxjpeg ^
    -lwxzlib ^
    -lwxregexu ^
    -lwxexpat

rem --- WINDOWS SYSTEM LIBS -------------------------------------------
set WINLIBS= ^
    -lshlwapi ^
    -lversion ^
    -lole32 ^
    -lshell32 ^
    -luuid ^
    -lrpcrt4 ^
    -luxtheme ^
    -lgdi32 ^
    -loleaut32 ^
    -lcomdlg32 ^
    -lcomctl32 ^
    -loleacc ^
    -lwinspool

rem --- MANIFEST -------------------------------------------------------
echo 1 24 UI\src\app.manifest > UI\src\manifest.rc
%MINGW%\bin\windres.exe UI\src\manifest.rc -O coff -o obj\manifest.o

rem --- ENSURE OBJ FOLDER ----------------------------------------------
if not exist obj mkdir obj

rem --- COMPILE --------------------------------------------------------
echo Compiling sources...
for /r Infrastructure %%f in (*.cpp) do (
    echo %%f
    %MINGW%\bin\g++.exe -std=c++17 -c "%%f" %INC% -o obj\%%~nf.o
)

for /r Application %%f in (*.cpp) do (
    echo %%f
    %MINGW%\bin\g++.exe -std=c++17 -c "%%f" %INC% -o obj\%%~nf.o
)

for /r ThirdParty\wxSQLite3\src %%f in (*.cpp) do (
    echo %%f
    %MINGW%\bin\g++.exe -std=c++17 -c "%%f" %INC% -o obj\%%~nf.o
)

for %%f in (UI\src\*.cpp) do (
    echo %%f
    %MINGW%\bin\g++.exe -std=c++17 -c %%f %INC% -o obj\%%~nf.o
)

rem --- LINK -----------------------------------------------------------
echo Linking...
%MINGW%\bin\g++.exe obj\*.o -o %OUT% ^
%LIB% %WXLIBS% %WINLIBS%

echo Build complete: %OUT%

endlocal
