#!/usr/bin/env python3
"""Insert 12 sample decks of 40 recall cards into a Merken database."""

import sqlite3
import sys
from datetime import date

# front, back, tags. Tags are comma-separated, matching Tag::Join.
DECKS = [
	{
		"name": "Spanish for the Road",
		"description": "Phrases for airports, cafés, streets, and hotels. Say the Spanish out loud before you flip the card.",
		"cards": [
			("Hello", "Hola", "greeting, essential"),
			("Good morning", "Buenos días", "greeting, time"),
			("Good afternoon", "Buenas tardes", "greeting, time"),
			("Good evening / good night", "Buenas noches", "greeting, time"),
			("Please", "Por favor", "polite, essential"),
			("Thank you", "Gracias", "polite, essential"),
			("You're welcome", "De nada", "polite, essential"),
			("Excuse me / sorry", "Perdón, or disculpe when addressing someone", "polite, essential"),
			("Yes", "Sí", "essential"),
			("No", "No", "essential"),
			("Where is the bathroom?", "¿Dónde está el baño?", "travel, question"),
			("How much does it cost?", "¿Cuánto cuesta?", "shopping, question"),
			("I would like…", "Quisiera…", "café, polite"),
			("The check, please", "La cuenta, por favor", "café, polite"),
			("I don't understand", "No entiendo", "conversation, essential"),
			("Do you speak English?", "¿Habla inglés?", "conversation, question"),
			("Can you help me?", "¿Me puede ayudar?", "travel, question"),
			("A table for two", "Una mesa para dos", "café"),
			("Water, please", "Agua, por favor", "café, essential"),
			("Without ice", "Sin hielo", "café"),
			("I am allergic to…", "Soy alérgico a… / Soy alérgica a…", "café, health"),
			("Left", "Izquierda", "directions"),
			("Right", "Derecha", "directions"),
			("Straight ahead", "Todo recto", "directions"),
			("Train station", "La estación de tren", "travel, place"),
			("Airport", "El aeropuerto", "travel, place"),
			("Ticket", "El boleto, or el billete in Spain", "travel"),
			("What time is it?", "¿Qué hora es?", "time, question"),
			("Today", "Hoy", "time"),
			("Tomorrow", "Mañana", "time"),
			("Yesterday", "Ayer", "time"),
			("Open", "Abierto", "sign"),
			("Closed", "Cerrado", "sign"),
			("I need a doctor", "Necesito un médico", "health, essential"),
			("Call the police", "Llame a la policía", "emergency"),
			("My name is…", "Me llamo…", "introduction"),
			("Nice to meet you", "Mucho gusto", "introduction"),
			("See you later", "Hasta luego", "greeting"),
			("How are you?", "¿Cómo está?", "greeting, question"),
			("I am lost", "Estoy perdido / Estoy perdida", "travel, essential"),
		],
	},
	{
		"name": "French Café and Street",
		"description": "French you can use the same day: ordering, asking the way, and being polite.",
		"cards": [
			("Hello", "Bonjour", "greeting, essential"),
			("Good evening", "Bonsoir", "greeting, time"),
			("Goodbye", "Au revoir", "greeting"),
			("Please", "S'il vous plaît", "polite, essential"),
			("Thank you", "Merci", "polite, essential"),
			("You're welcome", "Je vous en prie, or de rien", "polite"),
			("Excuse me", "Excusez-moi", "polite"),
			("Yes", "Oui", "essential"),
			("No", "Non", "essential"),
			("I would like a coffee", "Je voudrais un café", "café"),
			("A coffee with milk", "Un café au lait", "café"),
			("The bill, please", "L'addition, s'il vous plaît", "café"),
			("Water, still", "De l'eau plate", "café"),
			("Sparkling water", "De l'eau pétillante", "café"),
			("I am vegetarian", "Je suis végétarien / végétarienne", "café, diet"),
			("Without sugar", "Sans sucre", "café"),
			("Where is the metro?", "Où est le métro ?", "directions, question"),
			("Left", "À gauche", "directions"),
			("Right", "À droite", "directions"),
			("Straight ahead", "Tout droit", "directions"),
			("I am lost", "Je suis perdu / perdue", "travel"),
			("Do you speak English?", "Parlez-vous anglais ?", "conversation"),
			("I don't understand", "Je ne comprends pas", "conversation"),
			("Can you repeat that?", "Pouvez-vous répéter ?", "conversation"),
			("More slowly, please", "Plus lentement, s'il vous plaît", "conversation"),
			("How much is it?", "C'est combien ?", "shopping"),
			("Too expensive", "C'est trop cher", "shopping"),
			("I would like this one", "Je voudrais celui-ci / celle-ci", "shopping"),
			("Open", "Ouvert", "sign"),
			("Closed", "Fermé", "sign"),
			("Today", "Aujourd'hui", "time"),
			("Tomorrow", "Demain", "time"),
			("What time is it?", "Quelle heure est-il ?", "time"),
			("Train station", "La gare", "place"),
			("Airport", "L'aéroport", "place"),
			("A ticket to…", "Un billet pour…", "travel"),
			("My name is…", "Je m'appelle…", "introduction"),
			("Nice to meet you", "Enchanté / Enchantée", "introduction"),
			("See you soon", "À bientôt", "greeting"),
			("Help!", "Au secours !", "emergency"),
		],
	},
	{
		"name": "Japanese for Daily Life",
		"description": "Forty core words and phrases, with romaji and a short note on when to use them.",
		"cards": [
			("Hello", "Konnichiwa. Use ohayō gozaimasu in the morning.", "greeting"),
			("Thank you", "Arigatō gozaimasu. Arigatō is fine with friends.", "polite"),
			("Thanks for the meal, before eating", "Itadakimasu", "food, polite"),
			("Thanks for the meal, after eating", "Gochisōsama deshita", "food, polite"),
			("Excuse me / sorry", "Sumimasen", "polite, essential"),
			("Yes", "Hai", "essential"),
			("No", "Iie", "essential"),
			("Please give me this", "Kore o kudasai", "shopping"),
			("How much is it?", "Ikura desu ka?", "shopping, question"),
			("Where is the station?", "Eki wa doko desu ka?", "travel, question"),
			("Train station", "Eki", "place"),
			("This one", "Kore", "pointer"),
			("That one, near you", "Sore", "pointer"),
			("That one, over there", "Are", "pointer"),
			("Water", "Mizu", "food"),
			("Tea", "Ocha", "food"),
			("Delicious", "Oishii", "food"),
			("I don't eat meat", "Niku wa tabemasen", "food, diet"),
			("The check, please", "Okaikei o onegaishimasu", "food"),
			("Toilet", "Toire", "place"),
			("Left", "Hidari", "directions"),
			("Right", "Migi", "directions"),
			("Straight", "Massugu", "directions"),
			("Today", "Kyō", "time"),
			("Tomorrow", "Ashita", "time"),
			("Yesterday", "Kinō", "time"),
			("What time?", "Nan-ji desu ka?", "time, question"),
			("My name is…", "Watashi no namae wa … desu", "introduction"),
			("Nice to meet you", "Hajimemashite", "introduction"),
			("Please treat me well", "Yoroshiku onegaishimasu", "introduction, polite"),
			("Goodbye", "Sayōnara, or jaa ne with friends", "greeting"),
			("See you", "Mata ne", "greeting"),
			("I don't understand", "Wakarimasen", "conversation"),
			("Do you speak English?", "Eigo o hanasemasu ka?", "conversation"),
			("Help", "Tasukete", "emergency"),
			("Hospital", "Byōin", "place, health"),
			("Police", "Keisatsu", "emergency"),
			("Open", "Eigyō-chū, or aite imasu", "sign"),
			("Closed", "Junbichū for preparing, or shimatte imasu", "sign"),
			("One, two, three", "Ichi, ni, san", "number"),
		],
	},
	{
		"name": "World Capitals",
		"description": "Country on the front, capital on the back. A few notes flag cities that surprise people.",
		"cards": [
			("France", "Paris", "europe, capital"),
			("Germany", "Berlin", "europe, capital"),
			("Italy", "Rome", "europe, capital"),
			("Spain", "Madrid", "europe, capital"),
			("Portugal", "Lisbon", "europe, capital"),
			("Ireland", "Dublin", "europe, capital"),
			("United Kingdom", "London", "europe, capital"),
			("Norway", "Oslo", "europe, capital"),
			("Sweden", "Stockholm", "europe, capital"),
			("Finland", "Helsinki", "europe, capital"),
			("Poland", "Warsaw", "europe, capital"),
			("Ukraine", "Kyiv", "europe, capital"),
			("Greece", "Athens", "europe, capital"),
			("Switzerland", "Bern", "europe, capital"),
			("Iceland", "Reykjavík", "europe, capital"),
			("Turkey", "Ankara. Istanbul is the largest city, not the capital.", "asia, capital"),
			("Japan", "Tokyo", "asia, capital"),
			("China", "Beijing", "asia, capital"),
			("South Korea", "Seoul", "asia, capital"),
			("India", "New Delhi", "asia, capital"),
			("Thailand", "Bangkok", "asia, capital"),
			("Vietnam", "Hanoi", "asia, capital"),
			("Indonesia", "Jakarta", "asia, capital"),
			("Philippines", "Manila", "asia, capital"),
			("Australia", "Canberra. Sydney and Melbourne are larger.", "oceania, capital"),
			("New Zealand", "Wellington", "oceania, capital"),
			("Canada", "Ottawa", "americas, capital"),
			("Mexico", "Mexico City", "americas, capital"),
			("Brazil", "Brasília", "americas, capital"),
			("Argentina", "Buenos Aires", "americas, capital"),
			("Chile", "Santiago", "americas, capital"),
			("Peru", "Lima", "americas, capital"),
			("Colombia", "Bogotá", "americas, capital"),
			("Egypt", "Cairo", "africa, capital"),
			("Morocco", "Rabat. Casablanca is larger.", "africa, capital"),
			("Nigeria", "Abuja. Lagos is the largest city.", "africa, capital"),
			("Kenya", "Nairobi", "africa, capital"),
			("Ghana", "Accra", "africa, capital"),
			("South Africa", "Pretoria is the executive capital. Cape Town and Bloemfontein share other roles.", "africa, capital"),
			("Saudi Arabia", "Riyadh", "asia, capital"),
		],
	},
	{
		"name": "Human Body",
		"description": "What each structure does, in one plain sentence. Front is the name, back is the job.",
		"cards": [
			("Heart", "Pumps blood through the lungs and the rest of the body.", "organ, circulation"),
			("Lungs", "Exchange oxygen and carbon dioxide with the blood.", "organ, breathing"),
			("Trachea", "The windpipe that carries air from the larynx to the bronchi.", "breathing"),
			("Diaphragm", "The muscle under the lungs that drives breathing.", "breathing, muscle"),
			("Esophagus", "The tube that carries swallowed food to the stomach.", "digestion"),
			("Stomach", "Churns food and begins protein digestion with acid and enzymes.", "digestion, organ"),
			("Small intestine", "Where most digestion finishes and nutrients are absorbed.", "digestion"),
			("Large intestine", "Absorbs water and forms the remaining waste into stool.", "digestion"),
			("Liver", "Makes bile, stores glycogen, and processes many substances from the blood.", "organ, digestion"),
			("Gallbladder", "Stores and releases bile made by the liver.", "digestion"),
			("Pancreas", "Releases digestive enzymes and the hormones insulin and glucagon.", "organ, digestion"),
			("Kidneys", "Filter blood, balance water and salts, and make urine.", "organ, excretion"),
			("Spleen", "Filters blood and helps the immune system recycle old red cells.", "organ, immune"),
			("Brain", "Receives senses, plans movement, and holds memory and thought.", "organ, nervous"),
			("Neuron", "A nerve cell that sends electrical and chemical signals.", "nervous"),
			("Spinal cord", "Carries signals between the brain and the body and runs some reflexes.", "nervous"),
			("Aorta", "The largest artery, carrying oxygen-rich blood out of the left ventricle.", "circulation"),
			("Vena cava", "The large veins that return blood to the right atrium.", "circulation"),
			("Artery", "A vessel that carries blood away from the heart.", "circulation"),
			("Vein", "A vessel that carries blood back toward the heart.", "circulation"),
			("Capillary", "A tiny vessel where gases and nutrients pass into tissues.", "circulation"),
			("Red blood cell", "Carries oxygen using hemoglobin.", "blood"),
			("White blood cell", "A cell of the immune system that fights infection.", "blood, immune"),
			("Platelet", "A cell fragment that helps blood clot.", "blood"),
			("Skin", "The body's outer barrier, also used for touch and temperature control.", "organ"),
			("Femur", "The thigh bone, the longest bone in the body.", "bone"),
			("Humerus", "The bone of the upper arm.", "bone"),
			("Tibia", "The larger shin bone.", "bone"),
			("Radius", "The forearm bone on the thumb side.", "bone"),
			("Ulna", "The forearm bone on the little-finger side.", "bone"),
			("Skull", "The bones that protect the brain and form the face.", "bone"),
			("Ribs", "Curved bones that protect the heart and lungs.", "bone"),
			("Pelvis", "The hip bones that support the trunk and cradle organs.", "bone"),
			("Tendon", "Connects muscle to bone.", "connective"),
			("Ligament", "Connects bone to bone at a joint.", "connective"),
			("Cartilage", "Smooth, flexible tissue that cushions many joints.", "connective"),
			("Cornea", "The clear front window of the eye that bends incoming light.", "eye"),
			("Retina", "The light-sensitive layer at the back of the eye.", "eye"),
			("Cochlea", "The spiral inner-ear organ that turns sound into nerve signals.", "ear"),
			("Skin's epidermis", "The outer layer of skin, constantly replacing itself.", "skin"),
		],
	},
	{
		"name": "Elements You Meet",
		"description": "Symbol, name, and one reason the element shows up in ordinary life.",
		"cards": [
			("H", "Hydrogen. The lightest element, and the fuel of stars.", "symbol, gas"),
			("He", "Helium. An unreactive gas used in balloons and in cooling magnets.", "symbol, gas"),
			("Li", "Lithium. A soft metal used in rechargeable batteries.", "symbol, metal"),
			("Be", "Beryllium. A light, stiff metal used in aerospace parts.", "symbol, metal"),
			("B", "Boron. Used in borosilicate glass and in some detergents.", "symbol"),
			("C", "Carbon. The backbone of living molecules, and of coal, graphite, and diamond.", "symbol, life"),
			("N", "Nitrogen. Most of the air, and a key ingredient of proteins.", "symbol, gas"),
			("O", "Oxygen. The gas cells use to release energy from food.", "symbol, gas"),
			("F", "Fluorine. The most reactive halogen, added to some toothpastes as fluoride.", "symbol"),
			("Ne", "Neon. An inert gas that glows red-orange in signs.", "symbol, gas"),
			("Na", "Sodium. A metal that, as an ion, is essential in nerves and in table salt.", "symbol, metal"),
			("Mg", "Magnesium. A light metal in alloys, and a mineral in chlorophyll.", "symbol, metal"),
			("Al", "Aluminum. A light metal used for cans, foil, and aircraft.", "symbol, metal"),
			("Si", "Silicon. The semiconductor at the heart of computer chips, and a major part of sand.", "symbol"),
			("P", "Phosphorus. Needed in DNA, ATP, and bones.", "symbol, life"),
			("S", "Sulfur. A yellow solid found in proteins and in some minerals.", "symbol"),
			("Cl", "Chlorine. A reactive gas used, carefully, to disinfect water.", "symbol, gas"),
			("Ar", "Argon. An inert gas used as a protective atmosphere in welding.", "symbol, gas"),
			("K", "Potassium. An ion that nerves and muscles cannot do without.", "symbol, metal"),
			("Ca", "Calcium. The metal that makes bones and teeth hard.", "symbol, metal"),
			("Ti", "Titanium. A strong, light, corrosion-resistant metal.", "symbol, metal"),
			("Cr", "Chromium. Used to plate metal and in stainless steel.", "symbol, metal"),
			("Mn", "Manganese. Added to steel to make it tougher.", "symbol, metal"),
			("Fe", "Iron. The metal of steel, and the center of hemoglobin.", "symbol, metal"),
			("Co", "Cobalt. Used in magnets and in some blue pigments.", "symbol, metal"),
			("Ni", "Nickel. A tough metal in coins and stainless steel.", "symbol, metal"),
			("Cu", "Copper. An excellent conductor used in electrical wire.", "symbol, metal"),
			("Zn", "Zinc. Coats steel to stop rust, and is a needed trace mineral.", "symbol, metal"),
			("Br", "Bromine. A reddish liquid halogen at room temperature.", "symbol"),
			("Kr", "Krypton. An inert gas used in some high-performance lamps.", "symbol, gas"),
			("Ag", "Silver. The best electrical conductor among the metals.", "symbol, metal"),
			("Sn", "Tin. A soft metal used to coat steel cans.", "symbol, metal"),
			("I", "Iodine. Needed by the thyroid, and used as an antiseptic.", "symbol"),
			("Xe", "Xenon. A heavy inert gas used in some headlights and anesthesia.", "symbol, gas"),
			("Pt", "Platinum. A rare metal used in catalytic converters and jewelry.", "symbol, metal"),
			("Au", "Gold. A dense, unreactive metal prized for electronics and jewelry.", "symbol, metal"),
			("Hg", "Mercury. The only metal that is liquid at room temperature.", "symbol, metal"),
			("Pb", "Lead. A dense, soft metal. Exposure is toxic, especially to children.", "symbol, metal"),
			("Rn", "Radon. A radioactive noble gas that can collect in basements.", "symbol, gas"),
			("U", "Uranium. A heavy radioactive metal used as nuclear fuel.", "symbol, metal"),
		],
	},
	{
		"name": "Reading Music",
		"description": "The marks on a page of music, and what they tell a player to do.",
		"cards": [
			("Staff", "The five lines and four spaces where notes sit.", "notation"),
			("Treble clef", "The G clef. It puts G above middle C on the second line.", "clef"),
			("Bass clef", "The F clef. It puts F below middle C on the fourth line.", "clef"),
			("Alto clef", "A C clef that puts middle C on the middle line. Viola music uses it.", "clef"),
			("Whole note", "An open notehead worth four beats in 4/4.", "rhythm"),
			("Half note", "An open notehead with a stem, worth two beats in 4/4.", "rhythm"),
			("Quarter note", "A filled notehead with a stem, worth one beat in 4/4.", "rhythm"),
			("Eighth note", "A quarter note with one flag, worth half a beat in 4/4.", "rhythm"),
			("Sixteenth note", "A note with two flags, worth a quarter of a beat in 4/4.", "rhythm"),
			("Whole rest", "A rest hanging from the fourth line, worth four beats in 4/4.", "rhythm"),
			("Half rest", "A rest sitting on the third line, worth two beats in 4/4.", "rhythm"),
			("Quarter rest", "A squiggle rest worth one beat.", "rhythm"),
			("Dot after a note", "Adds half the note's value again. A dotted half note is three beats.", "rhythm"),
			("Tie", "A curved line joining two notes of the same pitch into one longer sound.", "rhythm"),
			("Time signature 4/4", "Four quarter-note beats in each measure.", "meter"),
			("Time signature 3/4", "Three quarter-note beats in each measure. A waltz meter.", "meter"),
			("Time signature 6/8", "Six eighth-note beats, usually felt as two groups of three.", "meter"),
			("Bar line", "A vertical line that marks the end of a measure.", "notation"),
			("Double bar", "Two bar lines that mark the end of a section or piece.", "notation"),
			("Sharp", "Raises a note by one half step.", "pitch"),
			("Flat", "Lowers a note by one half step.", "pitch"),
			("Natural", "Cancels a sharp or flat.", "pitch"),
			("Key signature", "The sharps or flats printed at the start, applied to every matching note.", "pitch"),
			("Scale", "A set of pitches in order, such as the major or natural minor scale.", "pitch"),
			("Interval", "The distance between two pitches, named by how many letter names it spans.", "pitch"),
			("Octave", "The interval of eight letter names. The notes sound like the same pitch class.", "pitch"),
			("Chord", "Three or more notes sounding together.", "harmony"),
			("Triad", "A three-note chord built from two stacked thirds.", "harmony"),
			("Major triad", "A chord with a major third on the bottom and a minor third on top.", "harmony"),
			("Minor triad", "A chord with a minor third on the bottom and a major third on top.", "harmony"),
			("Forte", "Play loud. Abbreviated f.", "dynamics"),
			("Piano, the dynamic", "Play soft. Abbreviated p.", "dynamics"),
			("Crescendo", "Gradually get louder.", "dynamics"),
			("Decrescendo", "Gradually get softer.", "dynamics"),
			("Tempo", "The speed of the beat.", "tempo"),
			("Allegro", "A fast, lively tempo.", "tempo"),
			("Andante", "A walking tempo, moderately slow.", "tempo"),
			("Adagio", "A slow tempo.", "tempo"),
			("Fermata", "Hold the note or rest longer than its written value.", "expression"),
			("Staccato", "A dot that means play the note short and detached.", "expression"),
		],
	},
	{
		"name": "Turning Points in U.S. History",
		"description": "An event on the front, the year and why it mattered on the back.",
		"cards": [
			("Declaration of Independence", "1776. The thirteen colonies declared themselves independent of Britain.", "founding"),
			("Constitution signed", "1787. Delegates in Philadelphia drafted the framework still used today.", "founding"),
			("Bill of Rights ratified", "1791. The first ten amendments listed core individual liberties.", "founding, rights"),
			("Louisiana Purchase", "1803. The United States bought a vast territory from France.", "expansion"),
			("Lewis and Clark expedition", "1804–1806. They mapped a route from the Missouri River to the Pacific.", "expansion"),
			("War of 1812 ends", "1815. The Treaty of Ghent had been signed in 1814; the war confirmed U.S. independence in practice.", "war"),
			("Missouri Compromise", "1820. It tried to balance free and slave states as the country grew.", "slavery"),
			("Indian Removal Act", "1830. It authorized forcing Native nations from the Southeast. The Trail of Tears followed.", "expansion, injustice"),
			("Seneca Falls Convention", "1848. A meeting that launched an organized movement for women's rights.", "rights"),
			("Compromise of 1850", "1850. A package of laws, including a harsh Fugitive Slave Act, that delayed the crisis over slavery.", "slavery"),
			("Dred Scott decision", "1857. The Supreme Court denied citizenship to Black people and struck at limits on slavery.", "slavery, court"),
			("Civil War begins", "1861. Confederate forces fired on Fort Sumter.", "war"),
			("Emancipation Proclamation", "1863. Lincoln declared enslaved people in rebelling states free.", "slavery, war"),
			("Gettysburg Address", "1863. Lincoln framed the war as a test of whether a democracy could endure.", "war"),
			("Civil War ends", "1865. Lee surrendered at Appomattox. Slavery was then abolished by the 13th Amendment.", "war"),
			("13th Amendment", "1865. It abolished slavery in the United States.", "rights"),
			("14th Amendment", "1868. It guaranteed citizenship and equal protection of the laws.", "rights"),
			("15th Amendment", "1870. It barred denying the vote on account of race.", "rights"),
			("Transcontinental railroad completed", "1869. The rails met at Promontory Summit, Utah.", "industry"),
			("Compromise of 1877", "1877. Federal troops left the South, and Reconstruction effectively ended.", "reconstruction"),
			("Chinese Exclusion Act", "1882. The first major U.S. law to ban immigration by nationality.", "immigration"),
			("Plessy v. Ferguson", "1896. The Court upheld racial segregation under 'separate but equal.'", "court, rights"),
			("Spanish-American War", "1898. A short war after which the U.S. gained overseas territories.", "war"),
			("Wright brothers' first flight", "1903. The first powered, controlled airplane flight, at Kitty Hawk.", "invention"),
			("17th Amendment", "1913. It provided for direct election of senators.", "reform"),
			("U.S. enters World War I", "1917. Congress declared war on Germany.", "war"),
			("19th Amendment", "1920. It prohibited denying the vote on account of sex.", "rights"),
			("Stock market crash", "1929. The October crash helped trigger the Great Depression.", "economy"),
			("Social Security Act", "1935. It created old-age insurance and other New Deal protections.", "reform"),
			("Pearl Harbor attacked", "1941. The attack brought the United States into World War II.", "war"),
			("D-Day", "1944. Allied forces landed in Normandy to open a western front.", "war"),
			("Brown v. Board of Education", "1954. The Court ruled that segregated public schools are unconstitutional.", "court, rights"),
			("Montgomery bus boycott", "1955–1956. A boycott after Rosa Parks's arrest helped launch the mass civil rights movement.", "rights"),
			("March on Washington", "1963. Hundreds of thousands gathered; King gave the 'I Have a Dream' speech.", "rights"),
			("Civil Rights Act", "1964. It outlawed discrimination in public accommodations and employment.", "rights"),
			("Voting Rights Act", "1965. It banned practices used to keep Black citizens from voting.", "rights"),
			("Moon landing", "1969. Apollo 11 put the first people on the Moon.", "science"),
			("Watergate resignations", "1974. President Nixon resigned rather than face certain impeachment.", "politics"),
			("Americans with Disabilities Act", "1990. It barred discrimination and required access in public life.", "rights"),
			("September 11 attacks", "2001. Terrorist attacks killed nearly 3,000 people and reshaped U.S. policy.", "war"),
		],
	},
	{
		"name": "Python You Can Use",
		"description": "Small, true facts about the language. Front is a question or a snippet's job, back is the answer.",
		"cards": [
			("What does len(\"hi\") return?", "2. len counts items in a sequence.", "builtin"),
			("How do you start a comment?", "With #. The rest of the line is ignored.", "syntax"),
			("What is the type of 3.14?", "float", "type"),
			("What is the type of \"3\"?", "str. Quotes make a string, even if the characters are digits.", "type"),
			("How do you turn the string \"12\" into an int?", "int(\"12\")", "conversion"),
			("What does 7 // 2 equal?", "3. // is floor division.", "operator"),
			("What does 7 % 2 equal?", "1. % is the remainder.", "operator"),
			("What does 2 ** 3 equal?", "8. ** is exponentiation.", "operator"),
			("How do you write a list of three numbers?", "[1, 2, 3]", "collection"),
			("How do you add an item to the end of a list?", "items.append(value)", "list"),
			("What does a list slice a[1:3] include?", "Indexes 1 and 2. The stop index is excluded.", "list"),
			("How do you write a dictionary of one pair?", "{\"name\": \"Ada\"}", "collection"),
			("How do you get a dictionary value safely?", "data.get(\"name\"), which returns None if the key is missing.", "dict"),
			("What does a tuple look like?", "(1, 2). Tuples cannot be changed after they are created.", "collection"),
			("What does a set do with duplicates?", "It keeps each value once. {1, 1, 2} is {1, 2}.", "collection"),
			("How do you write an if / else?", "if condition:\\n    ...\\nelse:\\n    ...", "control"),
			("What does range(3) produce?", "0, 1, 2. The stop value is not included.", "loop"),
			("How do you loop over a list?", "for item in items:", "loop"),
			("What does break do?", "It leaves the nearest loop immediately.", "loop"),
			("What does continue do?", "It skips the rest of this loop pass and starts the next one.", "loop"),
			("How do you define a function?", "def greet(name):", "function"),
			("What does return do?", "It sends a value back to the caller and ends the function.", "function"),
			("What is None?", "The value that means 'no value.' Functions with no return give None.", "type"),
			("How do you import the math module?", "import math", "module"),
			("How do you import one name?", "from math import sqrt", "module"),
			("What does f\"{name}\" do?", "It builds a string and inserts the value of name.", "string"),
			("How do you open a file for reading?", "open(path) or, better, with open(path) as handle:", "file"),
			("Why use with for a file?", "It closes the file even if an error happens inside the block.", "file"),
			("What does a try / except catch?", "Exceptions raised in the try block. except names the kind you handle.", "error"),
			("What is a list comprehension?", "A compact way to build a list: [n * 2 for n in nums]", "list"),
			("Are strings mutable?", "No. Methods like replace return a new string.", "string"),
			("Are lists mutable?", "Yes. append and item assignment change the same list.", "list"),
			("What does == test?", "Whether two values are equal.", "operator"),
			("What does is test?", "Whether two names refer to the same object.", "operator"),
			("What is a boolean?", "True or False.", "type"),
			("What does and require?", "Both sides must be true.", "logic"),
			("What does or require?", "At least one side must be true.", "logic"),
			("What does not do?", "It flips True to False and False to True.", "logic"),
			("How do you read input from the user?", "input(prompt), which always returns a string.", "builtin"),
			("What is PEP 8?", "Python's style guide for names, spacing, and layout.", "style"),
		],
	},
	{
		"name": "Seeing Art History",
		"description": "A movement or work on the front, and what to look for on the back.",
		"cards": [
			("Renaissance", "1400s–1500s Europe. Artists revived classical ideas and studied anatomy, perspective, and natural light.", "movement"),
			("Linear perspective", "Parallel lines are drawn so they meet at a vanishing point, creating depth.", "technique"),
			("Leonardo da Vinci", "A Renaissance painter and investigator. The Mona Lisa and The Last Supper are his best-known paintings.", "artist"),
			("Michelangelo's David", "A marble statue, finished in 1504, of the biblical hero before the fight.", "work"),
			("Sistine Chapel ceiling", "Michelangelo's frescoes, painted 1508–1512, including the Creation of Adam.", "work"),
			("Baroque", "1600s. Dramatic light, movement, and emotion. Caravaggio and Bernini are central.", "movement"),
			("Caravaggio", "A Baroque painter known for stark light against deep dark, called tenebrism.", "artist"),
			("Rembrandt", "A Dutch painter of portraits and biblical scenes, famous for warm light and honest faces.", "artist"),
			("Vermeer", "A Dutch painter of quiet interiors. Girl with a Pearl Earring is his most famous work.", "artist"),
			("Rococo", "Early 1700s. Light colors, curves, and playful scenes of leisure. Fragonard is a key name.", "movement"),
			("Neoclassicism", "Late 1700s. Calm, severe scenes drawn from Greece and Rome. Jacques-Louis David led it.", "movement"),
			("Romanticism", "Late 1700s–mid 1800s. Emotion, nature, and the sublime. Turner, Géricault, and Delacroix.", "movement"),
			("J. M. W. Turner", "A British painter of light, weather, and the sea, pushing toward abstraction.", "artist"),
			("Realism", "Mid 1800s. Ordinary workers and unidealized life. Courbet was a founder.", "movement"),
			("Impressionism", "1870s France. Painters worked outdoors to catch changing light. Monet, Renoir, Degas.", "movement"),
			("Claude Monet", "An Impressionist who painted series of haystacks, the Rouen cathedral, and water lilies.", "artist"),
			("Edgar Degas", "An Impressionist known for dancers, racetracks, and unusual viewpoints.", "artist"),
			("Post-Impressionism", "Late 1800s. Artists kept bright color but built more personal structure. Van Gogh, Cézanne, Gauguin.", "movement"),
			("Vincent van Gogh", "A Post-Impressionist who used thick, swirling paint. The Starry Night dates to 1889.", "artist"),
			("Paul Cézanne", "He built landscapes from patches of color and strongly influenced Cubism.", "artist"),
			("Art Nouveau", "About 1890–1910. Organic lines in posters, architecture, and objects. Mucha and Gaudí.", "movement"),
			("Fauvism", "Early 1900s. Wild, non-natural color. Matisse was the leading figure.", "movement"),
			("Cubism", "From 1907. Objects broken into shifting planes. Picasso and Braque invented it.", "movement"),
			("Pablo Picasso", "A founder of Cubism who kept reinventing his style across a very long career.", "artist"),
			("Les Demoiselles d'Avignon", "Picasso, 1907. A painting that shattered single-point perspective.", "work"),
			("Futurism", "Early 1900s Italy. Art that celebrated speed, machines, and modern life.", "movement"),
			("Dada", "During World War I. Anti-art that mocked reason and taste. Duchamp's readymades belong here.", "movement"),
			("Fountain", "Marcel Duchamp, 1917. A urinal signed and submitted as sculpture.", "work"),
			("Surrealism", "1920s on. Dream logic and the unconscious. Dalí, Magritte, and Kahlo connect to it.", "movement"),
			("Salvador Dalí", "A Surrealist painter of melting clocks and precise, dreamlike scenes.", "artist"),
			("Frida Kahlo", "A Mexican painter of unsparing self-portraits tied to pain, identity, and politics.", "artist"),
			("Abstract Expressionism", "1940s–1950s New York. Large gestures or fields of color. Pollock and Rothko.", "movement"),
			("Jackson Pollock", "He dripped and flung paint across canvases laid on the floor.", "artist"),
			("Pop art", "1950s–1960s. Fine art made from ads, comics, and products. Warhol and Lichtenstein.", "movement"),
			("Andy Warhol", "A Pop artist who repeated soup cans, celebrities, and disasters like mass-produced images.", "artist"),
			("Minimalism", "1960s. Simple geometric forms and industrial materials. Donald Judd is a key sculptor.", "movement"),
			("Impression, Sunrise", "Monet, 1872. The painting whose title a critic turned into the name Impressionism.", "work"),
			("The Night Watch", "Rembrandt, 1642. A huge civic-guard portrait full of movement and shadow.", "work"),
			("Guernica", "Picasso, 1937. A black, white, and gray mural protesting the bombing of a Basque town.", "work"),
			("The Great Wave", "Hokusai, about 1831. A Japanese woodblock print of a wave towering over boats, with Mount Fuji beyond.", "work"),
		],
	},
	{
		"name": "The Night Sky",
		"description": "What you are looking at, from the Moon out to the galaxies. One clear fact on each back.",
		"cards": [
			("Light-year", "The distance light travels in one year, about 9.5 trillion kilometers.", "measure"),
			("Astronomical unit", "The average Earth–Sun distance, about 150 million kilometers.", "measure"),
			("Sun", "The star at the center of our solar system. It is a yellow dwarf.", "star"),
			("Moon", "Earth's natural satellite. The same side always faces Earth.", "moon"),
			("Lunar phase", "The shape of the sunlit part of the Moon we can see, from new to full and back.", "moon"),
			("Solar eclipse", "The Moon passes between Earth and the Sun and blocks the Sun's light.", "event"),
			("Lunar eclipse", "Earth passes between the Sun and the Moon and Earth's shadow falls on the Moon.", "event"),
			("Mercury", "The smallest planet and the closest to the Sun. A year there lasts 88 Earth days.", "planet"),
			("Venus", "The hottest planet, wrapped in a thick carbon-dioxide atmosphere.", "planet"),
			("Earth", "The only planet known to host life. It has liquid water and one large moon.", "planet"),
			("Mars", "A cold desert world with the largest volcano and canyon in the solar system.", "planet"),
			("Jupiter", "The largest planet, a gas giant with a lasting storm called the Great Red Spot.", "planet"),
			("Saturn", "A gas giant circled by bright rings of ice and rock.", "planet"),
			("Uranus", "An ice giant that rotates on its side.", "planet"),
			("Neptune", "The farthest known planet, an ice giant with fierce winds.", "planet"),
			("Asteroid", "A rocky body, mostly orbiting between Mars and Jupiter.", "small body"),
			("Comet", "An icy body that grows a tail of gas and dust when it nears the Sun.", "small body"),
			("Meteor", "The streak of light when a space rock burns in the atmosphere. The rock itself is a meteoroid.", "small body"),
			("Meteorite", "A space rock that survives the fall and reaches the ground.", "small body"),
			("Star", "A ball of gas so massive that nuclear fusion shines in its core.", "star"),
			("Red giant", "A star that has swollen and cooled after exhausting the hydrogen in its core.", "star"),
			("White dwarf", "The dense, cooling core left when a Sun-like star sheds its outer layers.", "star"),
			("Supernova", "The explosion of a massive star, briefly outshining its whole galaxy.", "star"),
			("Neutron star", "The city-sized, ultra-dense remnant of some supernovae.", "star"),
			("Black hole", "A region where gravity is so strong that nothing, not even light, can escape.", "star"),
			("Galaxy", "A huge system of stars, gas, dust, and dark matter, bound by gravity.", "galaxy"),
			("Milky Way", "The spiral galaxy that contains our solar system.", "galaxy"),
			("Andromeda Galaxy", "The nearest large galaxy to the Milky Way, about 2.5 million light-years away.", "galaxy"),
			("Constellation", "A named pattern of stars, and the region of sky around it.", "sky"),
			("Orion", "A bright winter constellation marked by three stars in a straight belt.", "constellation"),
			("Polaris", "The North Star. Earth's north axis points near it, so it barely moves in the sky.", "star"),
			("Big Dipper", "A saucepan-shaped group of seven stars inside Ursa Major. It points toward Polaris.", "constellation"),
			("Sirius", "The brightest star in the night sky, in the constellation Canis Major.", "star"),
			("Light pollution", "Artificial light that washes out the night sky.", "observing"),
			("Telescope", "An instrument that gathers light so faint, distant objects can be seen.", "observing"),
			("Reflecting telescope", "A telescope that uses a mirror to collect light.", "observing"),
			("Refracting telescope", "A telescope that uses a lens to collect light.", "observing"),
			("Exoplanet", "A planet orbiting a star other than the Sun.", "planet"),
			("Habitable zone", "The range of distances from a star where liquid water could exist on a planet's surface.", "planet"),
			("International Space Station", "A habitable laboratory in low Earth orbit, continuously crewed since 2000.", "spaceflight"),
		],
	},
	{
		"name": "Kitchen Fundamentals",
		"description": "Techniques, doneness, and a few rules that keep food both good and safe.",
		"cards": [
			("Mise en place", "Prepare and measure every ingredient before you start cooking.", "habit"),
			("Sauté", "Cook quickly in a little fat over fairly high heat, stirring often.", "technique"),
			("Sweat", "Cook vegetables gently in fat until soft, without browning them.", "technique"),
			("Sear", "Brown the surface of meat or vegetables over high heat.", "technique"),
			("Braise", "Brown food, then cook it slowly, partly covered, in a little liquid.", "technique"),
			("Simmer", "Cook in liquid just below a boil, with small lazy bubbles.", "technique"),
			("Boil", "Cook in liquid at a full rolling boil.", "technique"),
			("Blanch", "Boil briefly, then plunge into ice water to stop the cooking.", "technique"),
			("Roast", "Cook uncovered in the oven with dry heat, usually uncovered.", "technique"),
			("Bake", "Cook in the oven with dry heat. The word is used for breads, cakes, and casseroles.", "technique"),
			("Broil", "Cook with intense heat from above.", "technique"),
			("Poach", "Cook gently in liquid held below a simmer.", "technique"),
			("Steam", "Cook with the vapor from boiling water, not in the water itself.", "technique"),
			("Deglaze", "Add liquid to a hot pan to dissolve the browned bits into a sauce.", "technique"),
			("Reduce", "Boil a liquid so water evaporates and the flavor concentrates.", "technique"),
			("Emulsify", "Whisk two liquids that normally separate, such as oil and vinegar, into a stable mix.", "technique"),
			("Dice", "Cut into small, even cubes.", "knife"),
			("Mince", "Cut much finer than a dice.", "knife"),
			("Julienne", "Cut into thin matchsticks.", "knife"),
			("Chiffonade", "Stack leaves, roll them, and slice into thin ribbons.", "knife"),
			("Al dente", "Pasta cooked until tender but still firm to the bite.", "doneness"),
			("Safe temperature for poultry", "165°F / 74°C in the thickest part.", "safety"),
			("Danger zone", "Between 40°F and 140°F (4°C and 60°C), where bacteria grow quickly.", "safety"),
			("Refrigerate leftovers within", "Two hours, or one hour if the room is above 90°F / 32°C.", "safety"),
			("Salt early for beans and meat", "Salt draws out moisture at first, then helps food stay juicy and taste seasoned through.", "seasoning"),
			("Bloom spices", "Warm ground spices briefly in fat so their flavor opens up.", "seasoning"),
			("Taste as you go", "Season in layers and taste before serving. You cannot fix what you never checked.", "habit"),
			("Rest a roast", "Let it sit after cooking so the juices settle back into the meat.", "doneness"),
			("Carryover cooking", "Food keeps cooking for a few minutes after it leaves the heat.", "doneness"),
			("Soft peak", "Whipped cream or egg white that flops over when you lift the whisk.", "baking"),
			("Stiff peak", "A whip that stands up straight when you lift the whisk.", "baking"),
			("Creaming", "Beating butter and sugar until pale and fluffy, so a cake rises evenly.", "baking"),
			("Fold", "Combine a light mixture into a heavier one with a gentle lift, so you do not knock out air.", "baking"),
			("Knead", "Work dough until the gluten stretches and the dough becomes smooth and elastic.", "baking"),
			("Proof", "Let yeast dough rise until it grows in volume.", "baking"),
			("Maillard reaction", "The browning of proteins and sugars that creates roasted, savory flavor.", "science"),
			("Acid balances fat", "A squeeze of lemon or a splash of vinegar makes a rich dish taste brighter.", "seasoning"),
			("Sharp knife is safer", "A sharp blade bites instead of slipping, so you use less force.", "knife, safety"),
			("Board for raw meat", "Use a separate board, or wash it well, before cutting food you will eat raw.", "safety"),
			("Salted water for pasta", "It should taste pleasantly salty, like the sea, so the pasta is seasoned as it cooks.", "habit"),
		],
	},
]


def main() -> int:
	if len(sys.argv) != 2:
		print("usage: seed_decks.py DATABASE", file=sys.stderr)
		return 1

	expected = 40
	for deck in DECKS:
		count = len(deck["cards"])
		if count != expected:
			print(f"{deck['name']} has {count} cards, expected {expected}", file=sys.stderr)
			return 1

	created_at = date.today().isoformat()
	connection = sqlite3.connect(sys.argv[1])
	try:
		connection.execute("PRAGMA foreign_keys = ON")
		with connection:
			for deck in DECKS:
				cursor = connection.execute(
					"INSERT INTO decks (name, description, created_at) VALUES (?, ?, ?)",
					(deck["name"], deck["description"], created_at),
				)
				deck_id = cursor.lastrowid
				connection.executemany(
					"""
					INSERT INTO cards (
						deck_id, front, back, tags, card_type, choices,
						interval_days, ease_factor, repetition_count,
						next_review_date, last_reviewed_date
					) VALUES (?, ?, ?, ?, 0, '', 0, 2.5, 0, '', '')
					""",
					[(deck_id, front, back, tags) for front, back, tags in deck["cards"]],
				)
		decks, cards = connection.execute(
			"SELECT (SELECT COUNT(*) FROM decks), (SELECT COUNT(*) FROM cards)"
		).fetchone()
	finally:
		connection.close()

	print(f"Seeded {len(DECKS)} decks, {len(DECKS) * expected} cards.")
	print(f"Database now has {decks} decks and {cards} cards.")
	return 0


if __name__ == "__main__":
	raise SystemExit(main())
